### PR TITLE
Blender

### PR DESCRIPTION
**Pull request by fabioharams**

### CODE REVIEW

**Comment by annatisch** [comment]
Hi @fabioharams  - are there any new changes here? Or is this a merge from my fork?

**Comment by fabioharams** [comment]
Hi @annatisch , you can delete this conflict.

**Comment by e-crins** [comment]
Hi. oh oooh.... Doe sthis mean no more development for this plugin? Is there any type of replacement for the plugin? It was promissing...

**Comment by annatisch** [comment]
@e-crins -no this project is still live! I just haven't had the time to work on it recently.
If there's any pressing bugs or feature requests you have though please let me know. :)

**Pull request closed without merging**
